# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SpriteHelperOMYSNd.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QCheckBox,
    QDoubleSpinBox, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QMainWindow, QPushButton,
    QScrollArea, QSizePolicy, QSpinBox, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        #MainWindow.resize(1608, 902)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(16)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(546, 273))
        MainWindow.setMaximumSize(QSize(2180, 1090))
        MainWindow.setSizeIncrement(QSize(16, 9))
        MainWindow.setBaseSize(QSize(872, 436))
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle(u"Megamix Sprite Helper")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.Europe))
        MainWindow.setAnimated(True)
        self.grid = QWidget(MainWindow)
        self.grid.setObjectName(u"grid")
        self.grid.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(16)
        sizePolicy1.setVerticalStretch(9)
        sizePolicy1.setHeightForWidth(self.grid.sizePolicy().hasHeightForWidth())
        self.grid.setSizePolicy(sizePolicy1)
        self.grid.setMinimumSize(QSize(0, 0))
        self.grid.setSizeIncrement(QSize(16, 9))
        self.grid.setBaseSize(QSize(0, 0))
        self.grid.setAutoFillBackground(False)
        self.horizontalLayout_5 = QHBoxLayout(self.grid)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.image_grid = QGridLayout()
        self.image_grid.setSpacing(5)
        self.image_grid.setObjectName(u"image_grid")
        self.image_grid.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.image_grid.setContentsMargins(0, 0, 0, 0)
        self.mm_song_selector_preview = QLabel(self.grid)
        self.mm_song_selector_preview.setObjectName(u"mm_song_selector_preview")
        sizePolicy1.setHeightForWidth(self.mm_song_selector_preview.sizePolicy().hasHeightForWidth())
        self.mm_song_selector_preview.setSizePolicy(sizePolicy1)
        self.mm_song_selector_preview.setMinimumSize(QSize(256, 144))
        self.mm_song_selector_preview.setMaximumSize(QSize(1920, 1680))
        self.mm_song_selector_preview.setSizeIncrement(QSize(16, 9))
        self.mm_song_selector_preview.setBaseSize(QSize(640, 360))
        self.mm_song_selector_preview.setScaledContents(True)

        self.image_grid.addWidget(self.mm_song_selector_preview, 1, 0, 1, 1)

        self.ft_result_preview = QLabel(self.grid)
        self.ft_result_preview.setObjectName(u"ft_result_preview")
        sizePolicy1.setHeightForWidth(self.ft_result_preview.sizePolicy().hasHeightForWidth())
        self.ft_result_preview.setSizePolicy(sizePolicy1)
        self.ft_result_preview.setMinimumSize(QSize(256, 144))
        self.ft_result_preview.setMaximumSize(QSize(1920, 1080))
        self.ft_result_preview.setSizeIncrement(QSize(16, 9))
        self.ft_result_preview.setBaseSize(QSize(640, 360))
        self.ft_result_preview.setScaledContents(True)

        self.image_grid.addWidget(self.ft_result_preview, 1, 1, 1, 1)

        self.ft_song_selector_preview = QLabel(self.grid)
        self.ft_song_selector_preview.setObjectName(u"ft_song_selector_preview")
        sizePolicy1.setHeightForWidth(self.ft_song_selector_preview.sizePolicy().hasHeightForWidth())
        self.ft_song_selector_preview.setSizePolicy(sizePolicy1)
        self.ft_song_selector_preview.setMinimumSize(QSize(256, 144))
        self.ft_song_selector_preview.setMaximumSize(QSize(1920, 1080))
        self.ft_song_selector_preview.setSizeIncrement(QSize(16, 9))
        self.ft_song_selector_preview.setBaseSize(QSize(640, 360))
        self.ft_song_selector_preview.setScaledContents(True)

        self.image_grid.addWidget(self.ft_song_selector_preview, 0, 1, 1, 1)

        self.mm_result_preview = QLabel(self.grid)
        self.mm_result_preview.setObjectName(u"mm_result_preview")
        sizePolicy1.setHeightForWidth(self.mm_result_preview.sizePolicy().hasHeightForWidth())
        self.mm_result_preview.setSizePolicy(sizePolicy1)
        self.mm_result_preview.setMinimumSize(QSize(256, 144))
        self.mm_result_preview.setMaximumSize(QSize(1920, 1080))
        self.mm_result_preview.setSizeIncrement(QSize(16, 9))
        self.mm_result_preview.setBaseSize(QSize(640, 360))
        self.mm_result_preview.setScaledContents(True)

        self.image_grid.addWidget(self.mm_result_preview, 0, 0, 1, 1)

        self.image_grid.setRowStretch(0, 2)
        self.image_grid.setColumnStretch(0, 2)

        self.horizontalLayout_5.addLayout(self.image_grid)

        self.load_buttons_box = QVBoxLayout()
        self.load_buttons_box.setSpacing(5)
        self.load_buttons_box.setObjectName(u"load_buttons_box")
        self.load_buttons_box.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.load_buttons_box_row1 = QHBoxLayout()
        self.load_buttons_box_row1.setSpacing(5)
        self.load_buttons_box_row1.setObjectName(u"load_buttons_box_row1")
        self.load_background_button = QPushButton(self.grid)
        self.load_background_button.setObjectName(u"load_background_button")

        self.load_buttons_box_row1.addWidget(self.load_background_button)

        self.load_logo_button = QPushButton(self.grid)
        self.load_logo_button.setObjectName(u"load_logo_button")

        self.load_buttons_box_row1.addWidget(self.load_logo_button)


        self.load_buttons_box.addLayout(self.load_buttons_box_row1)

        self.load_buttons_box_row2 = QHBoxLayout()
        self.load_buttons_box_row2.setSpacing(5)
        self.load_buttons_box_row2.setObjectName(u"load_buttons_box_row2")
        self.load_thumbnail_button = QPushButton(self.grid)
        self.load_thumbnail_button.setObjectName(u"load_thumbnail_button")

        self.load_buttons_box_row2.addWidget(self.load_thumbnail_button)

        self.load_jacket_button = QPushButton(self.grid)
        self.load_jacket_button.setObjectName(u"load_jacket_button")

        self.load_buttons_box_row2.addWidget(self.load_jacket_button)


        self.load_buttons_box.addLayout(self.load_buttons_box_row2)

        self.load_buttons_box_row3 = QHBoxLayout()
        self.load_buttons_box_row3.setSpacing(5)
        self.load_buttons_box_row3.setObjectName(u"load_buttons_box_row3")

        self.load_buttons_box.addLayout(self.load_buttons_box_row3)

        self.image_edit_scroll_area = QScrollArea(self.grid)
        self.image_edit_scroll_area.setObjectName(u"image_edit_scroll_area")
        self.image_edit_scroll_area.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.image_edit_scroll_area.sizePolicy().hasHeightForWidth())
        self.image_edit_scroll_area.setSizePolicy(sizePolicy2)
        self.image_edit_scroll_area.setAutoFillBackground(False)
        self.image_edit_scroll_area.setFrameShape(QFrame.Shape.StyledPanel)
        self.image_edit_scroll_area.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_edit_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.image_edit_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.image_edit_scroll_area.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.image_edit_scroll_area.setWidgetResizable(True)
        self.image_edit_scroll_area.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft)
        self.image_edit_area_widget_properties = QWidget()
        self.image_edit_area_widget_properties.setObjectName(u"image_edit_area_widget_properties")
        self.image_edit_area_widget_properties.setGeometry(QRect(0, -238, 199, 900))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(100)
        sizePolicy3.setHeightForWidth(self.image_edit_area_widget_properties.sizePolicy().hasHeightForWidth())
        self.image_edit_area_widget_properties.setSizePolicy(sizePolicy3)
        self.image_edit_area_widget_properties.setMinimumSize(QSize(0, 900))
        self.image_edit_area_widget_properties.setMaximumSize(QSize(10000, 100000))
        self.image_edit_area_widget_properties.setSizeIncrement(QSize(0, -31072))
        self.image_edit_area_widget_properties.setBaseSize(QSize(0, -31072))
        self.image_edit_area_widget_properties.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.image_edit_area_widget_properties.setAutoFillBackground(True)
        self.jacket_rotation_label = QLabel(self.image_edit_area_widget_properties)
        self.jacket_rotation_label.setObjectName(u"jacket_rotation_label")
        self.jacket_rotation_label.setGeometry(QRect(0, 110, 1080, 18))
        self.thumbnail_rotation_label = QLabel(self.image_edit_area_widget_properties)
        self.thumbnail_rotation_label.setObjectName(u"thumbnail_rotation_label")
        self.thumbnail_rotation_label.setGeometry(QRect(0, 785, 1080, 18))
        self.logo_vertical_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.logo_vertical_offset_spinbox.setObjectName(u"logo_vertical_offset_spinbox")
        self.logo_vertical_offset_spinbox.setGeometry(QRect(0, 528, 197, 27))
        self.logo_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_vertical_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.jacket_vertical_offset_spinbox.setObjectName(u"jacket_vertical_offset_spinbox")
        self.jacket_vertical_offset_spinbox.setGeometry(QRect(0, 78, 197, 27))
        self.jacket_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_vertical_offset_spinbox.setMinimum(-500)
        self.jacket_vertical_offset_spinbox.setMaximum(500)
        self.logo_horizontal_offset = QLabel(self.image_edit_area_widget_properties)
        self.logo_horizontal_offset.setObjectName(u"logo_horizontal_offset")
        self.logo_horizontal_offset.setGeometry(QRect(0, 450, 1080, 18))
        self.logo_horizontal_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.logo_horizontal_offset_spinbox.setObjectName(u"logo_horizontal_offset_spinbox")
        self.logo_horizontal_offset_spinbox.setGeometry(QRect(0, 473, 197, 27))
        self.logo_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.thumbnail_vertical_offset_label = QLabel(self.image_edit_area_widget_properties)
        self.thumbnail_vertical_offset_label.setObjectName(u"thumbnail_vertical_offset_label")
        self.thumbnail_vertical_offset_label.setGeometry(QRect(0, 730, 1080, 18))
        self.background_vertical_offset_label = QLabel(self.image_edit_area_widget_properties)
        self.background_vertical_offset_label.setObjectName(u"background_vertical_offset_label")
        self.background_vertical_offset_label.setGeometry(QRect(0, 280, 1080, 18))
        self.thumbnail_horizontal_offset_label = QLabel(self.image_edit_area_widget_properties)
        self.thumbnail_horizontal_offset_label.setObjectName(u"thumbnail_horizontal_offset_label")
        self.thumbnail_horizontal_offset_label.setGeometry(QRect(0, 675, 1080, 18))
        self.jacket_horizontal_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.jacket_horizontal_offset_spinbox.setObjectName(u"jacket_horizontal_offset_spinbox")
        self.jacket_horizontal_offset_spinbox.setGeometry(QRect(0, 23, 197, 27))
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.jacket_horizontal_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.jacket_horizontal_offset_spinbox.setSizePolicy(sizePolicy4)
        self.jacket_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_horizontal_offset_spinbox.setMinimum(-500)
        self.jacket_horizontal_offset_spinbox.setMaximum(500)
        self.thumbnail_horizontal_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.thumbnail_horizontal_offset_spinbox.setObjectName(u"thumbnail_horizontal_offset_spinbox")
        self.thumbnail_horizontal_offset_spinbox.setGeometry(QRect(0, 698, 197, 27))
        self.thumbnail_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_zoom_spinbox = QDoubleSpinBox(self.image_edit_area_widget_properties)
        self.background_zoom_spinbox.setObjectName(u"background_zoom_spinbox")
        self.background_zoom_spinbox.setGeometry(QRect(0, 413, 197, 27))
        self.background_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_zoom_spinbox.setMinimum(0.010000000000000)
        self.background_zoom_spinbox.setMaximum(1.000000000000000)
        self.background_zoom_spinbox.setSingleStep(0.010000000000000)
        self.background_zoom_spinbox.setValue(1.000000000000000)
        self.jacket_rotation_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.jacket_rotation_spinbox.setObjectName(u"jacket_rotation_spinbox")
        self.jacket_rotation_spinbox.setGeometry(QRect(0, 133, 197, 27))
        self.jacket_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_rotation_spinbox.setWrapping(True)
        self.jacket_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.jacket_rotation_spinbox.setMinimum(-180)
        self.jacket_rotation_spinbox.setMaximum(180)
        self.background_rotation_label = QLabel(self.image_edit_area_widget_properties)
        self.background_rotation_label.setObjectName(u"background_rotation_label")
        self.background_rotation_label.setGeometry(QRect(0, 335, 1080, 18))
        self.thumbnail_rotation_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.thumbnail_rotation_spinbox.setObjectName(u"thumbnail_rotation_spinbox")
        self.thumbnail_rotation_spinbox.setGeometry(QRect(0, 808, 197, 27))
        self.thumbnail_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.thumbnail_rotation_spinbox.setWrapping(True)
        self.thumbnail_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.thumbnail_rotation_spinbox.setMinimum(-180)
        self.thumbnail_rotation_spinbox.setMaximum(180)
        self.logo_zoom_spinbox = QDoubleSpinBox(self.image_edit_area_widget_properties)
        self.logo_zoom_spinbox.setObjectName(u"logo_zoom_spinbox")
        self.logo_zoom_spinbox.setGeometry(QRect(0, 638, 197, 27))
        self.logo_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.logo_zoom_spinbox.setMinimum(0.010000000000000)
        self.logo_zoom_spinbox.setMaximum(1.000000000000000)
        self.logo_zoom_spinbox.setSingleStep(0.010000000000000)
        self.logo_zoom_spinbox.setValue(1.000000000000000)
        self.jacket_horizontal_offset_label = QLabel(self.image_edit_area_widget_properties)
        self.jacket_horizontal_offset_label.setObjectName(u"jacket_horizontal_offset_label")
        self.jacket_horizontal_offset_label.setGeometry(QRect(0, 0, 1080, 18))
        self.jacket_zoom_spinbox = QDoubleSpinBox(self.image_edit_area_widget_properties)
        self.jacket_zoom_spinbox.setObjectName(u"jacket_zoom_spinbox")
        self.jacket_zoom_spinbox.setGeometry(QRect(0, 188, 197, 27))
        self.jacket_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_zoom_spinbox.setDecimals(2)
        self.jacket_zoom_spinbox.setMinimum(0.010000000000000)
        self.jacket_zoom_spinbox.setMaximum(1.000000000000000)
        self.jacket_zoom_spinbox.setSingleStep(0.010000000000000)
        self.jacket_zoom_spinbox.setValue(1.000000000000000)
        self.jacket_zoom_label = QLabel(self.image_edit_area_widget_properties)
        self.jacket_zoom_label.setObjectName(u"jacket_zoom_label")
        self.jacket_zoom_label.setGeometry(QRect(0, 165, 1080, 18))
        self.background_horizontal_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.background_horizontal_offset_spinbox.setObjectName(u"background_horizontal_offset_spinbox")
        self.background_horizontal_offset_spinbox.setGeometry(QRect(0, 248, 197, 27))
        self.background_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_horizontal_offset_spinbox.setWrapping(False)
        self.thumbnail_zoom_spinbox = QDoubleSpinBox(self.image_edit_area_widget_properties)
        self.thumbnail_zoom_spinbox.setObjectName(u"thumbnail_zoom_spinbox")
        self.thumbnail_zoom_spinbox.setGeometry(QRect(0, 863, 197, 27))
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.thumbnail_zoom_spinbox.sizePolicy().hasHeightForWidth())
        self.thumbnail_zoom_spinbox.setSizePolicy(sizePolicy5)
        self.thumbnail_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.thumbnail_zoom_spinbox.setMinimum(0.010000000000000)
        self.thumbnail_zoom_spinbox.setMaximum(1.000000000000000)
        self.thumbnail_zoom_spinbox.setSingleStep(0.010000000000000)
        self.thumbnail_zoom_spinbox.setValue(1.000000000000000)
        self.logo_zoom_label = QLabel(self.image_edit_area_widget_properties)
        self.logo_zoom_label.setObjectName(u"logo_zoom_label")
        self.logo_zoom_label.setGeometry(QRect(0, 615, 1080, 18))
        self.thumbnail_zoom_label = QLabel(self.image_edit_area_widget_properties)
        self.thumbnail_zoom_label.setObjectName(u"thumbnail_zoom_label")
        self.thumbnail_zoom_label.setGeometry(QRect(0, 840, 1080, 18))
        self.jacket_vertical_offset_label = QLabel(self.image_edit_area_widget_properties)
        self.jacket_vertical_offset_label.setObjectName(u"jacket_vertical_offset_label")
        self.jacket_vertical_offset_label.setGeometry(QRect(0, 55, 1080, 18))
        self.logo_vertical_offset_label = QLabel(self.image_edit_area_widget_properties)
        self.logo_vertical_offset_label.setObjectName(u"logo_vertical_offset_label")
        self.logo_vertical_offset_label.setGeometry(QRect(0, 505, 1080, 18))
        self.thumbnail_vertical_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.thumbnail_vertical_offset_spinbox.setObjectName(u"thumbnail_vertical_offset_spinbox")
        self.thumbnail_vertical_offset_spinbox.setGeometry(QRect(0, 753, 197, 27))
        self.thumbnail_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_rotation_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.background_rotation_spinbox.setObjectName(u"background_rotation_spinbox")
        self.background_rotation_spinbox.setGeometry(QRect(0, 358, 197, 27))
        self.background_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_rotation_spinbox.setWrapping(True)
        self.background_rotation_spinbox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.background_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.background_rotation_spinbox.setMinimum(-180)
        self.background_rotation_spinbox.setMaximum(180)
        self.background_horizontal_offset_label = QLabel(self.image_edit_area_widget_properties)
        self.background_horizontal_offset_label.setObjectName(u"background_horizontal_offset_label")
        self.background_horizontal_offset_label.setGeometry(QRect(0, 225, 1080, 18))
        self.logo_rotation_label = QLabel(self.image_edit_area_widget_properties)
        self.logo_rotation_label.setObjectName(u"logo_rotation_label")
        self.logo_rotation_label.setGeometry(QRect(0, 560, 1080, 18))
        self.logo_rotation_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.logo_rotation_spinbox.setObjectName(u"logo_rotation_spinbox")
        self.logo_rotation_spinbox.setGeometry(QRect(0, 583, 197, 27))
        self.logo_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.logo_rotation_spinbox.setWrapping(True)
        self.logo_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.logo_rotation_spinbox.setMinimum(-180)
        self.logo_rotation_spinbox.setValue(0)
        self.background_vertical_offset_spinbox = QSpinBox(self.image_edit_area_widget_properties)
        self.background_vertical_offset_spinbox.setObjectName(u"background_vertical_offset_spinbox")
        self.background_vertical_offset_spinbox.setGeometry(QRect(0, 303, 197, 27))
        self.background_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_zoom_label = QLabel(self.image_edit_area_widget_properties)
        self.background_zoom_label.setObjectName(u"background_zoom_label")
        self.background_zoom_label.setGeometry(QRect(0, 390, 1080, 18))
        self.image_edit_scroll_area.setWidget(self.image_edit_area_widget_properties)

        self.load_buttons_box.addWidget(self.image_edit_scroll_area)

        self.copy_to_clipboard_button = QPushButton(self.grid)
        self.copy_to_clipboard_button.setObjectName(u"copy_to_clipboard_button")

        self.load_buttons_box.addWidget(self.copy_to_clipboard_button)

        self.export_thumbnail_button = QPushButton(self.grid)
        self.export_thumbnail_button.setObjectName(u"export_thumbnail_button")

        self.load_buttons_box.addWidget(self.export_thumbnail_button)

        self.export_logo_button = QPushButton(self.grid)
        self.export_logo_button.setObjectName(u"export_logo_button")

        self.load_buttons_box.addWidget(self.export_logo_button)

        self.export_background_jacket_button = QPushButton(self.grid)
        self.export_background_jacket_button.setObjectName(u"export_background_jacket_button")

        self.load_buttons_box.addWidget(self.export_background_jacket_button)

        self.fix_jacket_edges_check_box = QCheckBox(self.grid)
        self.fix_jacket_edges_check_box.setObjectName(u"fix_jacket_edges_check_box")
        self.fix_jacket_edges_check_box.setChecked(True)

        self.load_buttons_box.addWidget(self.fix_jacket_edges_check_box)


        self.horizontalLayout_5.addLayout(self.load_buttons_box)

        MainWindow.setCentralWidget(self.grid)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.mm_song_selector_preview.setText("")
        self.ft_result_preview.setText("")
        self.ft_song_selector_preview.setText("")
        self.mm_result_preview.setText("")
        self.load_background_button.setText(QCoreApplication.translate("MainWindow", u"Load Background", None))
        self.load_logo_button.setText(QCoreApplication.translate("MainWindow", u"Load Logo", None))
        self.load_thumbnail_button.setText(QCoreApplication.translate("MainWindow", u"Load Thumbnail", None))
        self.load_jacket_button.setText(QCoreApplication.translate("MainWindow", u"Load Jacket", None))
        self.jacket_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Rotation", None))
        self.thumbnail_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Rotation", None))
        self.logo_horizontal_offset.setText(QCoreApplication.translate("MainWindow", u"Logo Horizontal Offset", None))
        self.thumbnail_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Vertical Offset", None))
        self.background_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Background Vertical Offset", None))
        self.thumbnail_horizontal_offset_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Horizontal Offset", None))
        self.background_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.jacket_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.background_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Background Rotation", None))
        self.thumbnail_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.logo_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.jacket_horizontal_offset_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Horizontal Offset", None))
        self.jacket_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.jacket_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Zoom", None))
        self.thumbnail_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.logo_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Logo Zoom", None))
        self.thumbnail_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Zoom", None))
        self.jacket_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Vertical Offset", None))
        self.logo_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Logo Vertical Offset", None))
        self.background_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.background_horizontal_offset_label.setText(QCoreApplication.translate("MainWindow", u"Background Horizontal Offset", None))
        self.logo_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Logo Rotation", None))
        self.logo_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.background_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Background Zoom", None))
        self.copy_to_clipboard_button.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
        self.export_thumbnail_button.setText(QCoreApplication.translate("MainWindow", u"Export Thumbnail", None))
        self.export_logo_button.setText(QCoreApplication.translate("MainWindow", u"Export Logo", None))
        self.export_background_jacket_button.setText(QCoreApplication.translate("MainWindow", u"Export Background/Jacket", None))
        self.fix_jacket_edges_check_box.setText(QCoreApplication.translate("MainWindow", u"Fix jacket edges on export", None))
        pass
    # retranslateUi

