# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SpriteHelperAobJvY.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QCheckBox,
    QDoubleSpinBox, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QMainWindow, QPushButton,
    QScrollArea, QSizePolicy, QSpacerItem, QSpinBox,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.resize(1200, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1200, 600))
        MainWindow.setSizeIncrement(QSize(0, 0))
        MainWindow.setBaseSize(QSize(1200, 600))
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle(u"Megamix Sprite Helper")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.Europe))
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.grid = QWidget(MainWindow)
        self.grid.setObjectName(u"grid")
        self.grid.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.grid.sizePolicy().hasHeightForWidth())
        self.grid.setSizePolicy(sizePolicy1)
        self.grid.setMinimumSize(QSize(0, 0))
        self.grid.setSizeIncrement(QSize(0, 0))
        self.grid.setBaseSize(QSize(0, 0))
        self.grid.setAutoFillBackground(False)
        self.horizontalLayout_5 = QHBoxLayout(self.grid)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.image_grid = QGridLayout()
        self.image_grid.setSpacing(5)
        self.image_grid.setObjectName(u"image_grid")
        self.image_grid.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.image_grid.setContentsMargins(0, 0, 0, 0)
        self.ft_song_selector_preview = QLabel(self.grid)
        self.ft_song_selector_preview.setObjectName(u"ft_song_selector_preview")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(1)
        sizePolicy2.setHeightForWidth(self.ft_song_selector_preview.sizePolicy().hasHeightForWidth())
        self.ft_song_selector_preview.setSizePolicy(sizePolicy2)
        self.ft_song_selector_preview.setMinimumSize(QSize(256, 144))
        self.ft_song_selector_preview.setMaximumSize(QSize(1920, 1080))
        self.ft_song_selector_preview.setSizeIncrement(QSize(0, 0))
        self.ft_song_selector_preview.setBaseSize(QSize(640, 360))
        self.ft_song_selector_preview.setScaledContents(True)

        self.image_grid.addWidget(self.ft_song_selector_preview, 0, 1, 1, 1)

        self.mm_result_preview = QLabel(self.grid)
        self.mm_result_preview.setObjectName(u"mm_result_preview")
        sizePolicy2.setHeightForWidth(self.mm_result_preview.sizePolicy().hasHeightForWidth())
        self.mm_result_preview.setSizePolicy(sizePolicy2)
        self.mm_result_preview.setMinimumSize(QSize(256, 144))
        self.mm_result_preview.setMaximumSize(QSize(1920, 1080))
        self.mm_result_preview.setSizeIncrement(QSize(0, 0))
        self.mm_result_preview.setBaseSize(QSize(640, 360))
        self.mm_result_preview.setScaledContents(True)

        self.image_grid.addWidget(self.mm_result_preview, 1, 0, 1, 1)

        self.mm_song_selector_preview = QLabel(self.grid)
        self.mm_song_selector_preview.setObjectName(u"mm_song_selector_preview")
        sizePolicy2.setHeightForWidth(self.mm_song_selector_preview.sizePolicy().hasHeightForWidth())
        self.mm_song_selector_preview.setSizePolicy(sizePolicy2)
        self.mm_song_selector_preview.setMinimumSize(QSize(256, 144))
        self.mm_song_selector_preview.setMaximumSize(QSize(1920, 1080))
        self.mm_song_selector_preview.setSizeIncrement(QSize(0, 0))
        self.mm_song_selector_preview.setBaseSize(QSize(640, 360))
        self.mm_song_selector_preview.setScaledContents(True)

        self.image_grid.addWidget(self.mm_song_selector_preview, 0, 0, 1, 1)

        self.ft_result_preview = QLabel(self.grid)
        self.ft_result_preview.setObjectName(u"ft_result_preview")
        sizePolicy2.setHeightForWidth(self.ft_result_preview.sizePolicy().hasHeightForWidth())
        self.ft_result_preview.setSizePolicy(sizePolicy2)
        self.ft_result_preview.setMinimumSize(QSize(256, 144))
        self.ft_result_preview.setMaximumSize(QSize(1920, 1080))
        self.ft_result_preview.setSizeIncrement(QSize(0, 0))
        self.ft_result_preview.setBaseSize(QSize(640, 360))
        self.ft_result_preview.setScaledContents(True)

        self.image_grid.addWidget(self.ft_result_preview, 1, 1, 1, 1)


        self.horizontalLayout_5.addLayout(self.image_grid)

        self.load_buttons_box = QVBoxLayout()
        self.load_buttons_box.setSpacing(5)
        self.load_buttons_box.setObjectName(u"load_buttons_box")
        self.load_buttons_box.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.load_buttons_box_row1 = QHBoxLayout()
        self.load_buttons_box_row1.setSpacing(5)
        self.load_buttons_box_row1.setObjectName(u"load_buttons_box_row1")
        self.load_background_button = QPushButton(self.grid)
        self.load_background_button.setObjectName(u"load_background_button")

        self.load_buttons_box_row1.addWidget(self.load_background_button)

        self.load_logo_button = QPushButton(self.grid)
        self.load_logo_button.setObjectName(u"load_logo_button")

        self.load_buttons_box_row1.addWidget(self.load_logo_button)


        self.load_buttons_box.addLayout(self.load_buttons_box_row1)

        self.load_buttons_box_row2 = QHBoxLayout()
        self.load_buttons_box_row2.setSpacing(5)
        self.load_buttons_box_row2.setObjectName(u"load_buttons_box_row2")
        self.load_thumbnail_button = QPushButton(self.grid)
        self.load_thumbnail_button.setObjectName(u"load_thumbnail_button")

        self.load_buttons_box_row2.addWidget(self.load_thumbnail_button)

        self.load_jacket_button = QPushButton(self.grid)
        self.load_jacket_button.setObjectName(u"load_jacket_button")

        self.load_buttons_box_row2.addWidget(self.load_jacket_button)


        self.load_buttons_box.addLayout(self.load_buttons_box_row2)

        self.has_logo_checkbox = QCheckBox(self.grid)
        self.has_logo_checkbox.setObjectName(u"has_logo_checkbox")
        self.has_logo_checkbox.setCheckable(True)
        self.has_logo_checkbox.setChecked(True)

        self.load_buttons_box.addWidget(self.has_logo_checkbox)

        self.load_buttons_box_row3 = QHBoxLayout()
        self.load_buttons_box_row3.setSpacing(5)
        self.load_buttons_box_row3.setObjectName(u"load_buttons_box_row3")

        self.load_buttons_box.addLayout(self.load_buttons_box_row3)

        self.image_edit_scroll_area = QScrollArea(self.grid)
        self.image_edit_scroll_area.setObjectName(u"image_edit_scroll_area")
        self.image_edit_scroll_area.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.image_edit_scroll_area.sizePolicy().hasHeightForWidth())
        self.image_edit_scroll_area.setSizePolicy(sizePolicy3)
        self.image_edit_scroll_area.setAutoFillBackground(False)
        self.image_edit_scroll_area.setFrameShape(QFrame.Shape.StyledPanel)
        self.image_edit_scroll_area.setFrameShadow(QFrame.Shadow.Sunken)
        self.image_edit_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.image_edit_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.image_edit_scroll_area.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.image_edit_scroll_area.setWidgetResizable(True)
        self.image_edit_scroll_area.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft)
        self.image_edit_area_widget_properties = QWidget()
        self.image_edit_area_widget_properties.setObjectName(u"image_edit_area_widget_properties")
        self.image_edit_area_widget_properties.setGeometry(QRect(0, -431, 199, 905))
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.image_edit_area_widget_properties.sizePolicy().hasHeightForWidth())
        self.image_edit_area_widget_properties.setSizePolicy(sizePolicy4)
        self.image_edit_area_widget_properties.setMinimumSize(QSize(0, 905))
        self.image_edit_area_widget_properties.setMaximumSize(QSize(16777215, 16777215))
        self.image_edit_area_widget_properties.setSizeIncrement(QSize(0, -31072))
        self.image_edit_area_widget_properties.setBaseSize(QSize(0, -31072))
        self.image_edit_area_widget_properties.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        self.image_edit_area_widget_properties.setAutoFillBackground(True)
        self.verticalLayoutWidget_3 = QWidget(self.image_edit_area_widget_properties)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(0, 0, 286, 901))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.jacket_horizontal_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.jacket_horizontal_offset_label.setObjectName(u"jacket_horizontal_offset_label")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.jacket_horizontal_offset_label.sizePolicy().hasHeightForWidth())
        self.jacket_horizontal_offset_label.setSizePolicy(sizePolicy5)
        self.jacket_horizontal_offset_label.setMaximumSize(QSize(16777215, 16777215))
        font = QFont()
        font.setPointSize(9)
        self.jacket_horizontal_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.jacket_horizontal_offset_label)

        self.jacket_horizontal_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.jacket_horizontal_offset_spinbox.setObjectName(u"jacket_horizontal_offset_spinbox")
        self.jacket_horizontal_offset_spinbox.setEnabled(False)
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.jacket_horizontal_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.jacket_horizontal_offset_spinbox.setSizePolicy(sizePolicy6)
        self.jacket_horizontal_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.jacket_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_horizontal_offset_spinbox.setMinimum(0)
        self.jacket_horizontal_offset_spinbox.setMaximum(0)

        self.verticalLayout_2.addWidget(self.jacket_horizontal_offset_spinbox)

        self.jacket_vertical_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.jacket_vertical_offset_label.setObjectName(u"jacket_vertical_offset_label")
        sizePolicy5.setHeightForWidth(self.jacket_vertical_offset_label.sizePolicy().hasHeightForWidth())
        self.jacket_vertical_offset_label.setSizePolicy(sizePolicy5)
        self.jacket_vertical_offset_label.setMaximumSize(QSize(16777215, 16777215))
        self.jacket_vertical_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.jacket_vertical_offset_label)

        self.jacket_vertical_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.jacket_vertical_offset_spinbox.setObjectName(u"jacket_vertical_offset_spinbox")
        self.jacket_vertical_offset_spinbox.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.jacket_vertical_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.jacket_vertical_offset_spinbox.setSizePolicy(sizePolicy6)
        self.jacket_vertical_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.jacket_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_vertical_offset_spinbox.setMinimum(0)
        self.jacket_vertical_offset_spinbox.setMaximum(0)

        self.verticalLayout_2.addWidget(self.jacket_vertical_offset_spinbox)

        self.jacket_rotation_label = QLabel(self.verticalLayoutWidget_3)
        self.jacket_rotation_label.setObjectName(u"jacket_rotation_label")
        sizePolicy5.setHeightForWidth(self.jacket_rotation_label.sizePolicy().hasHeightForWidth())
        self.jacket_rotation_label.setSizePolicy(sizePolicy5)
        self.jacket_rotation_label.setMaximumSize(QSize(16777215, 16777215))
        self.jacket_rotation_label.setFont(font)

        self.verticalLayout_2.addWidget(self.jacket_rotation_label)

        self.jacket_rotation_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.jacket_rotation_spinbox.setObjectName(u"jacket_rotation_spinbox")
        sizePolicy6.setHeightForWidth(self.jacket_rotation_spinbox.sizePolicy().hasHeightForWidth())
        self.jacket_rotation_spinbox.setSizePolicy(sizePolicy6)
        self.jacket_rotation_spinbox.setMaximumSize(QSize(160, 16777215))
        self.jacket_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_rotation_spinbox.setWrapping(True)
        self.jacket_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.jacket_rotation_spinbox.setMinimum(-180)
        self.jacket_rotation_spinbox.setMaximum(180)

        self.verticalLayout_2.addWidget(self.jacket_rotation_spinbox)

        self.jacket_zoom_label = QLabel(self.verticalLayoutWidget_3)
        self.jacket_zoom_label.setObjectName(u"jacket_zoom_label")
        sizePolicy5.setHeightForWidth(self.jacket_zoom_label.sizePolicy().hasHeightForWidth())
        self.jacket_zoom_label.setSizePolicy(sizePolicy5)
        self.jacket_zoom_label.setMaximumSize(QSize(16777215, 16777215))
        self.jacket_zoom_label.setFont(font)

        self.verticalLayout_2.addWidget(self.jacket_zoom_label)

        self.jacket_zoom_spinbox = QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.jacket_zoom_spinbox.setObjectName(u"jacket_zoom_spinbox")
        self.jacket_zoom_spinbox.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.jacket_zoom_spinbox.sizePolicy().hasHeightForWidth())
        self.jacket_zoom_spinbox.setSizePolicy(sizePolicy6)
        self.jacket_zoom_spinbox.setMaximumSize(QSize(160, 16777215))
        self.jacket_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.jacket_zoom_spinbox.setAccelerated(True)
        self.jacket_zoom_spinbox.setDecimals(3)
        self.jacket_zoom_spinbox.setMinimum(1.000000000000000)
        self.jacket_zoom_spinbox.setMaximum(1.000000000000000)
        self.jacket_zoom_spinbox.setSingleStep(0.001000000000000)
        self.jacket_zoom_spinbox.setValue(1.000000000000000)

        self.verticalLayout_2.addWidget(self.jacket_zoom_spinbox)

        self.background_horizontal_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.background_horizontal_offset_label.setObjectName(u"background_horizontal_offset_label")
        sizePolicy5.setHeightForWidth(self.background_horizontal_offset_label.sizePolicy().hasHeightForWidth())
        self.background_horizontal_offset_label.setSizePolicy(sizePolicy5)
        self.background_horizontal_offset_label.setMaximumSize(QSize(16777215, 16777215))
        self.background_horizontal_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.background_horizontal_offset_label)

        self.background_horizontal_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.background_horizontal_offset_spinbox.setObjectName(u"background_horizontal_offset_spinbox")
        self.background_horizontal_offset_spinbox.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.background_horizontal_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.background_horizontal_offset_spinbox.setSizePolicy(sizePolicy6)
        self.background_horizontal_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.background_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_horizontal_offset_spinbox.setWrapping(False)
        self.background_horizontal_offset_spinbox.setMaximum(0)

        self.verticalLayout_2.addWidget(self.background_horizontal_offset_spinbox)

        self.background_vertical_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.background_vertical_offset_label.setObjectName(u"background_vertical_offset_label")
        sizePolicy5.setHeightForWidth(self.background_vertical_offset_label.sizePolicy().hasHeightForWidth())
        self.background_vertical_offset_label.setSizePolicy(sizePolicy5)
        self.background_vertical_offset_label.setMaximumSize(QSize(16777215, 16777215))
        self.background_vertical_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.background_vertical_offset_label)

        self.background_vertical_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.background_vertical_offset_spinbox.setObjectName(u"background_vertical_offset_spinbox")
        self.background_vertical_offset_spinbox.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.background_vertical_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.background_vertical_offset_spinbox.setSizePolicy(sizePolicy6)
        self.background_vertical_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.background_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_vertical_offset_spinbox.setMaximum(0)

        self.verticalLayout_2.addWidget(self.background_vertical_offset_spinbox)

        self.background_rotation_label = QLabel(self.verticalLayoutWidget_3)
        self.background_rotation_label.setObjectName(u"background_rotation_label")
        sizePolicy5.setHeightForWidth(self.background_rotation_label.sizePolicy().hasHeightForWidth())
        self.background_rotation_label.setSizePolicy(sizePolicy5)
        self.background_rotation_label.setMaximumSize(QSize(16777215, 16777215))
        self.background_rotation_label.setFont(font)

        self.verticalLayout_2.addWidget(self.background_rotation_label)

        self.background_rotation_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.background_rotation_spinbox.setObjectName(u"background_rotation_spinbox")
        sizePolicy6.setHeightForWidth(self.background_rotation_spinbox.sizePolicy().hasHeightForWidth())
        self.background_rotation_spinbox.setSizePolicy(sizePolicy6)
        self.background_rotation_spinbox.setMaximumSize(QSize(160, 16777215))
        self.background_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_rotation_spinbox.setWrapping(True)
        self.background_rotation_spinbox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.background_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.background_rotation_spinbox.setProperty(u"showGroupSeparator", False)
        self.background_rotation_spinbox.setMinimum(-180)
        self.background_rotation_spinbox.setMaximum(180)

        self.verticalLayout_2.addWidget(self.background_rotation_spinbox)

        self.background_zoom_label = QLabel(self.verticalLayoutWidget_3)
        self.background_zoom_label.setObjectName(u"background_zoom_label")
        sizePolicy5.setHeightForWidth(self.background_zoom_label.sizePolicy().hasHeightForWidth())
        self.background_zoom_label.setSizePolicy(sizePolicy5)
        self.background_zoom_label.setMaximumSize(QSize(16777215, 16777215))
        self.background_zoom_label.setFont(font)

        self.verticalLayout_2.addWidget(self.background_zoom_label)

        self.background_zoom_spinbox = QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.background_zoom_spinbox.setObjectName(u"background_zoom_spinbox")
        self.background_zoom_spinbox.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.background_zoom_spinbox.sizePolicy().hasHeightForWidth())
        self.background_zoom_spinbox.setSizePolicy(sizePolicy6)
        self.background_zoom_spinbox.setMaximumSize(QSize(160, 16777215))
        self.background_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.background_zoom_spinbox.setAccelerated(True)
        self.background_zoom_spinbox.setDecimals(3)
        self.background_zoom_spinbox.setMinimum(1.000000000000000)
        self.background_zoom_spinbox.setMaximum(1.000000000000000)
        self.background_zoom_spinbox.setSingleStep(0.001000000000000)
        self.background_zoom_spinbox.setValue(1.000000000000000)

        self.verticalLayout_2.addWidget(self.background_zoom_spinbox)

        self.logo_horizontal_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.logo_horizontal_offset_label.setObjectName(u"logo_horizontal_offset_label")
        self.logo_horizontal_offset_label.setEnabled(True)
        sizePolicy5.setHeightForWidth(self.logo_horizontal_offset_label.sizePolicy().hasHeightForWidth())
        self.logo_horizontal_offset_label.setSizePolicy(sizePolicy5)
        self.logo_horizontal_offset_label.setMaximumSize(QSize(16777215, 16777215))
        self.logo_horizontal_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.logo_horizontal_offset_label)

        self.logo_horizontal_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.logo_horizontal_offset_spinbox.setObjectName(u"logo_horizontal_offset_spinbox")
        self.logo_horizontal_offset_spinbox.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.logo_horizontal_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.logo_horizontal_offset_spinbox.setSizePolicy(sizePolicy6)
        self.logo_horizontal_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.logo_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.logo_horizontal_offset_spinbox.setMinimum(-435)
        self.logo_horizontal_offset_spinbox.setMaximum(435)

        self.verticalLayout_2.addWidget(self.logo_horizontal_offset_spinbox)

        self.logo_vertical_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.logo_vertical_offset_label.setObjectName(u"logo_vertical_offset_label")
        self.logo_vertical_offset_label.setEnabled(True)
        sizePolicy5.setHeightForWidth(self.logo_vertical_offset_label.sizePolicy().hasHeightForWidth())
        self.logo_vertical_offset_label.setSizePolicy(sizePolicy5)
        self.logo_vertical_offset_label.setMaximumSize(QSize(16777215, 16777215))
        self.logo_vertical_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.logo_vertical_offset_label)

        self.logo_vertical_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.logo_vertical_offset_spinbox.setObjectName(u"logo_vertical_offset_spinbox")
        self.logo_vertical_offset_spinbox.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.logo_vertical_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.logo_vertical_offset_spinbox.setSizePolicy(sizePolicy6)
        self.logo_vertical_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.logo_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.logo_vertical_offset_spinbox.setMinimum(-150)
        self.logo_vertical_offset_spinbox.setMaximum(150)

        self.verticalLayout_2.addWidget(self.logo_vertical_offset_spinbox)

        self.logo_rotation_label = QLabel(self.verticalLayoutWidget_3)
        self.logo_rotation_label.setObjectName(u"logo_rotation_label")
        self.logo_rotation_label.setEnabled(True)
        sizePolicy5.setHeightForWidth(self.logo_rotation_label.sizePolicy().hasHeightForWidth())
        self.logo_rotation_label.setSizePolicy(sizePolicy5)
        self.logo_rotation_label.setMaximumSize(QSize(16777215, 16777215))
        self.logo_rotation_label.setFont(font)

        self.verticalLayout_2.addWidget(self.logo_rotation_label)

        self.logo_rotation_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.logo_rotation_spinbox.setObjectName(u"logo_rotation_spinbox")
        self.logo_rotation_spinbox.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.logo_rotation_spinbox.sizePolicy().hasHeightForWidth())
        self.logo_rotation_spinbox.setSizePolicy(sizePolicy6)
        self.logo_rotation_spinbox.setMaximumSize(QSize(160, 16777215))
        self.logo_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.logo_rotation_spinbox.setWrapping(True)
        self.logo_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.logo_rotation_spinbox.setMinimum(-180)
        self.logo_rotation_spinbox.setValue(0)

        self.verticalLayout_2.addWidget(self.logo_rotation_spinbox)

        self.logo_zoom_label = QLabel(self.verticalLayoutWidget_3)
        self.logo_zoom_label.setObjectName(u"logo_zoom_label")
        self.logo_zoom_label.setEnabled(True)
        sizePolicy5.setHeightForWidth(self.logo_zoom_label.sizePolicy().hasHeightForWidth())
        self.logo_zoom_label.setSizePolicy(sizePolicy5)
        self.logo_zoom_label.setMaximumSize(QSize(16777215, 16777215))
        self.logo_zoom_label.setFont(font)

        self.verticalLayout_2.addWidget(self.logo_zoom_label)

        self.logo_zoom_spinbox = QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.logo_zoom_spinbox.setObjectName(u"logo_zoom_spinbox")
        self.logo_zoom_spinbox.setEnabled(True)
        sizePolicy6.setHeightForWidth(self.logo_zoom_spinbox.sizePolicy().hasHeightForWidth())
        self.logo_zoom_spinbox.setSizePolicy(sizePolicy6)
        self.logo_zoom_spinbox.setMaximumSize(QSize(160, 16777215))
        self.logo_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.logo_zoom_spinbox.setAccelerated(True)
        self.logo_zoom_spinbox.setDecimals(3)
        self.logo_zoom_spinbox.setMinimum(0.001000000000000)
        self.logo_zoom_spinbox.setMaximum(1.000000000000000)
        self.logo_zoom_spinbox.setSingleStep(0.001000000000000)
        self.logo_zoom_spinbox.setValue(1.000000000000000)

        self.verticalLayout_2.addWidget(self.logo_zoom_spinbox)

        self.thumbnail_horizontal_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.thumbnail_horizontal_offset_label.setObjectName(u"thumbnail_horizontal_offset_label")
        sizePolicy5.setHeightForWidth(self.thumbnail_horizontal_offset_label.sizePolicy().hasHeightForWidth())
        self.thumbnail_horizontal_offset_label.setSizePolicy(sizePolicy5)
        self.thumbnail_horizontal_offset_label.setMaximumSize(QSize(16777215, 16777215))
        self.thumbnail_horizontal_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.thumbnail_horizontal_offset_label)

        self.thumbnail_horizontal_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.thumbnail_horizontal_offset_spinbox.setObjectName(u"thumbnail_horizontal_offset_spinbox")
        sizePolicy6.setHeightForWidth(self.thumbnail_horizontal_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.thumbnail_horizontal_offset_spinbox.setSizePolicy(sizePolicy6)
        self.thumbnail_horizontal_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.thumbnail_horizontal_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.thumbnail_horizontal_offset_spinbox.setMaximum(27)

        self.verticalLayout_2.addWidget(self.thumbnail_horizontal_offset_spinbox)

        self.thumbnail_vertical_offset_label = QLabel(self.verticalLayoutWidget_3)
        self.thumbnail_vertical_offset_label.setObjectName(u"thumbnail_vertical_offset_label")
        sizePolicy5.setHeightForWidth(self.thumbnail_vertical_offset_label.sizePolicy().hasHeightForWidth())
        self.thumbnail_vertical_offset_label.setSizePolicy(sizePolicy5)
        self.thumbnail_vertical_offset_label.setMaximumSize(QSize(16777215, 16777215))
        self.thumbnail_vertical_offset_label.setFont(font)

        self.verticalLayout_2.addWidget(self.thumbnail_vertical_offset_label)

        self.thumbnail_vertical_offset_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.thumbnail_vertical_offset_spinbox.setObjectName(u"thumbnail_vertical_offset_spinbox")
        self.thumbnail_vertical_offset_spinbox.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.thumbnail_vertical_offset_spinbox.sizePolicy().hasHeightForWidth())
        self.thumbnail_vertical_offset_spinbox.setSizePolicy(sizePolicy6)
        self.thumbnail_vertical_offset_spinbox.setMaximumSize(QSize(160, 16777215))
        self.thumbnail_vertical_offset_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.thumbnail_vertical_offset_spinbox.setMaximum(0)

        self.verticalLayout_2.addWidget(self.thumbnail_vertical_offset_spinbox)

        self.thumbnail_rotation_label = QLabel(self.verticalLayoutWidget_3)
        self.thumbnail_rotation_label.setObjectName(u"thumbnail_rotation_label")
        sizePolicy5.setHeightForWidth(self.thumbnail_rotation_label.sizePolicy().hasHeightForWidth())
        self.thumbnail_rotation_label.setSizePolicy(sizePolicy5)
        self.thumbnail_rotation_label.setMaximumSize(QSize(16777215, 16777215))
        self.thumbnail_rotation_label.setFont(font)

        self.verticalLayout_2.addWidget(self.thumbnail_rotation_label)

        self.thumbnail_rotation_spinbox = QSpinBox(self.verticalLayoutWidget_3)
        self.thumbnail_rotation_spinbox.setObjectName(u"thumbnail_rotation_spinbox")
        sizePolicy6.setHeightForWidth(self.thumbnail_rotation_spinbox.sizePolicy().hasHeightForWidth())
        self.thumbnail_rotation_spinbox.setSizePolicy(sizePolicy6)
        self.thumbnail_rotation_spinbox.setMaximumSize(QSize(160, 16777215))
        self.thumbnail_rotation_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.thumbnail_rotation_spinbox.setWrapping(True)
        self.thumbnail_rotation_spinbox.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.thumbnail_rotation_spinbox.setMinimum(-180)
        self.thumbnail_rotation_spinbox.setMaximum(180)

        self.verticalLayout_2.addWidget(self.thumbnail_rotation_spinbox)

        self.thumbnail_zoom_label = QLabel(self.verticalLayoutWidget_3)
        self.thumbnail_zoom_label.setObjectName(u"thumbnail_zoom_label")
        sizePolicy5.setHeightForWidth(self.thumbnail_zoom_label.sizePolicy().hasHeightForWidth())
        self.thumbnail_zoom_label.setSizePolicy(sizePolicy5)
        self.thumbnail_zoom_label.setMaximumSize(QSize(16777215, 16777215))
        self.thumbnail_zoom_label.setFont(font)

        self.verticalLayout_2.addWidget(self.thumbnail_zoom_label)

        self.thumbnail_zoom_spinbox = QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.thumbnail_zoom_spinbox.setObjectName(u"thumbnail_zoom_spinbox")
        self.thumbnail_zoom_spinbox.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.thumbnail_zoom_spinbox.sizePolicy().hasHeightForWidth())
        self.thumbnail_zoom_spinbox.setSizePolicy(sizePolicy6)
        self.thumbnail_zoom_spinbox.setMaximumSize(QSize(160, 16777215))
        self.thumbnail_zoom_spinbox.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.thumbnail_zoom_spinbox.setAccelerated(True)
        self.thumbnail_zoom_spinbox.setDecimals(3)
        self.thumbnail_zoom_spinbox.setMinimum(1.000000000000000)
        self.thumbnail_zoom_spinbox.setMaximum(1.000000000000000)
        self.thumbnail_zoom_spinbox.setSingleStep(0.001000000000000)
        self.thumbnail_zoom_spinbox.setValue(1.000000000000000)

        self.verticalLayout_2.addWidget(self.thumbnail_zoom_spinbox)

        self.verticalSpacer = QSpacerItem(0, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.image_edit_scroll_area.setWidget(self.image_edit_area_widget_properties)

        self.load_buttons_box.addWidget(self.image_edit_scroll_area)

        self.export_to_label = QLabel(self.grid)
        self.export_to_label.setObjectName(u"export_to_label")
        self.export_to_label.setMaximumSize(QSize(80, 16777215))
        self.export_to_label.setScaledContents(False)

        self.load_buttons_box.addWidget(self.export_to_label)

        self.export_options_tab_widget = QTabWidget(self.grid)
        self.export_options_tab_widget.setObjectName(u"export_options_tab_widget")
        sizePolicy3.setHeightForWidth(self.export_options_tab_widget.sizePolicy().hasHeightForWidth())
        self.export_options_tab_widget.setSizePolicy(sizePolicy3)
        self.export_options_tab_widget.setMinimumSize(QSize(0, 0))
        self.export_options_tab_widget.setMaximumSize(QSize(16777215, 222))
        self.export_options_tab_widget.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.export_options_tab_widget.setTabPosition(QTabWidget.TabPosition.North)
        self.export_options_tab_widget.setTabShape(QTabWidget.TabShape.Rounded)
        self.export_options_tab_widget.setElideMode(Qt.TextElideMode.ElideNone)
        self.export_options_tab_widget.setUsesScrollButtons(True)
        self.export_options_tab_widget.setDocumentMode(True)
        self.export_options_tab_widget.setTabsClosable(False)
        self.export_options_tab_widget.setMovable(False)
        self.export_options_image_tab = QWidget()
        self.export_options_image_tab.setObjectName(u"export_options_image_tab")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Ignored)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.export_options_image_tab.sizePolicy().hasHeightForWidth())
        self.export_options_image_tab.setSizePolicy(sizePolicy7)
        self.verticalLayoutWidget = QWidget(self.export_options_image_tab)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 201, 191))
        self.image_tab_vertical_layout = QVBoxLayout(self.verticalLayoutWidget)
        self.image_tab_vertical_layout.setSpacing(5)
        self.image_tab_vertical_layout.setObjectName(u"image_tab_vertical_layout")
        self.image_tab_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.copy_to_clipboard_button = QPushButton(self.verticalLayoutWidget)
        self.copy_to_clipboard_button.setObjectName(u"copy_to_clipboard_button")
        self.copy_to_clipboard_button.setMaximumSize(QSize(195, 16777215))
        self.copy_to_clipboard_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.image_tab_vertical_layout.addWidget(self.copy_to_clipboard_button)

        self.export_thumbnail_button = QPushButton(self.verticalLayoutWidget)
        self.export_thumbnail_button.setObjectName(u"export_thumbnail_button")
        self.export_thumbnail_button.setMaximumSize(QSize(195, 16777215))
        self.export_thumbnail_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.image_tab_vertical_layout.addWidget(self.export_thumbnail_button)

        self.export_logo_button = QPushButton(self.verticalLayoutWidget)
        self.export_logo_button.setObjectName(u"export_logo_button")
        self.export_logo_button.setMaximumSize(QSize(195, 16777215))
        self.export_logo_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.image_tab_vertical_layout.addWidget(self.export_logo_button)

        self.export_background_jacket_button = QPushButton(self.verticalLayoutWidget)
        self.export_background_jacket_button.setObjectName(u"export_background_jacket_button")
        self.export_background_jacket_button.setMaximumSize(QSize(195, 16777215))
        self.export_background_jacket_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.image_tab_vertical_layout.addWidget(self.export_background_jacket_button)

        self.export_options_tab_widget.addTab(self.export_options_image_tab, "")
        self.export_options_game_tab = QWidget()
        self.export_options_game_tab.setObjectName(u"export_options_game_tab")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.export_options_game_tab.sizePolicy().hasHeightForWidth())
        self.export_options_game_tab.setSizePolicy(sizePolicy8)
        self.verticalLayoutWidget_2 = QWidget(self.export_options_game_tab)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 0, 201, 191))
        self.game_tab_vertical_layout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.game_tab_vertical_layout.setObjectName(u"game_tab_vertical_layout")
        self.game_tab_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.song_id_label = QLabel(self.verticalLayoutWidget_2)
        self.song_id_label.setObjectName(u"song_id_label")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.song_id_label.sizePolicy().hasHeightForWidth())
        self.song_id_label.setSizePolicy(sizePolicy9)

        self.game_tab_vertical_layout.addWidget(self.song_id_label)

        self.song_id_spinbox = QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.song_id_spinbox.setObjectName(u"song_id_spinbox")
        self.song_id_spinbox.setMaximumSize(QSize(160, 16777215))
        self.song_id_spinbox.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.song_id_spinbox.setDecimals(0)
        self.song_id_spinbox.setMinimum(1.000000000000000)
        self.song_id_spinbox.setMaximum(4294967295.000000000000000)

        self.game_tab_vertical_layout.addWidget(self.song_id_spinbox)

        self.export_bg_jk_logo_farc_button = QPushButton(self.verticalLayoutWidget_2)
        self.export_bg_jk_logo_farc_button.setObjectName(u"export_bg_jk_logo_farc_button")
        self.export_bg_jk_logo_farc_button.setMaximumSize(QSize(195, 16777215))
        self.export_bg_jk_logo_farc_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.game_tab_vertical_layout.addWidget(self.export_bg_jk_logo_farc_button)

        self.export_thumbnail_farc_button = QPushButton(self.verticalLayoutWidget_2)
        self.export_thumbnail_farc_button.setObjectName(u"export_thumbnail_farc_button")
        self.export_thumbnail_farc_button.setMaximumSize(QSize(195, 16777215))
        self.export_thumbnail_farc_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.game_tab_vertical_layout.addWidget(self.export_thumbnail_farc_button)

        self.generate_spr_db_button = QPushButton(self.verticalLayoutWidget_2)
        self.generate_spr_db_button.setObjectName(u"generate_spr_db_button")
        self.generate_spr_db_button.setMaximumSize(QSize(195, 16777215))
        self.generate_spr_db_button.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self.game_tab_vertical_layout.addWidget(self.generate_spr_db_button)

        self.export_options_tab_widget.addTab(self.export_options_game_tab, "")

        self.load_buttons_box.addWidget(self.export_options_tab_widget)


        self.horizontalLayout_5.addLayout(self.load_buttons_box)

        MainWindow.setCentralWidget(self.grid)

        self.retranslateUi(MainWindow)

        self.export_options_tab_widget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.ft_song_selector_preview.setText("")
        self.mm_result_preview.setText("")
        self.mm_song_selector_preview.setText("")
        self.ft_result_preview.setText("")
        self.load_background_button.setText(QCoreApplication.translate("MainWindow", u"Load Background", None))
        self.load_logo_button.setText(QCoreApplication.translate("MainWindow", u"Load Logo", None))
        self.load_thumbnail_button.setText(QCoreApplication.translate("MainWindow", u"Load Thumbnail", None))
        self.load_jacket_button.setText(QCoreApplication.translate("MainWindow", u"Load Jacket", None))
        self.has_logo_checkbox.setText(QCoreApplication.translate("MainWindow", u"Has logo?", None))
        self.jacket_horizontal_offset_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Horizontal Offset", None))
        self.jacket_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Vertical Offset", None))
        self.jacket_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Rotation", None))
        self.jacket_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.jacket_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Jacket Zoom", None))
        self.jacket_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.background_horizontal_offset_label.setText(QCoreApplication.translate("MainWindow", u"Background Horizontal Offset", None))
        self.background_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Background Vertical Offset", None))
        self.background_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Background Rotation", None))
        self.background_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.background_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Background Zoom", None))
        self.background_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.logo_horizontal_offset_label.setText(QCoreApplication.translate("MainWindow", u"Logo Horizontal Offset", None))
        self.logo_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Logo Vertical Offset", None))
        self.logo_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Logo Rotation", None))
        self.logo_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.logo_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Logo Zoom", None))
        self.logo_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.thumbnail_horizontal_offset_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Horizontal Offset", None))
        self.thumbnail_vertical_offset_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Vertical Offset", None))
        self.thumbnail_rotation_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Rotation", None))
        self.thumbnail_rotation_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.thumbnail_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Thumbnail Zoom", None))
        self.thumbnail_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"x", None))
        self.export_to_label.setText(QCoreApplication.translate("MainWindow", u"Export to...", None))
        self.copy_to_clipboard_button.setText(QCoreApplication.translate("MainWindow", u"Copy to clipboard", None))
        self.export_thumbnail_button.setText(QCoreApplication.translate("MainWindow", u"Export Thumbnail", None))
        self.export_logo_button.setText(QCoreApplication.translate("MainWindow", u"Export Logo", None))
        self.export_background_jacket_button.setText(QCoreApplication.translate("MainWindow", u"Export Background/Jacket", None))
        self.export_options_tab_widget.setTabText(self.export_options_tab_widget.indexOf(self.export_options_image_tab), QCoreApplication.translate("MainWindow", u"Image", None))
        self.song_id_label.setText(QCoreApplication.translate("MainWindow", u"Song ID:", None))
        self.export_bg_jk_logo_farc_button.setText(QCoreApplication.translate("MainWindow", u"Export BG/JK/Logo Farc", None))
        self.export_thumbnail_farc_button.setText(QCoreApplication.translate("MainWindow", u"Export Thumbnail Farc", None))
        self.generate_spr_db_button.setText(QCoreApplication.translate("MainWindow", u"Generate Sprite Database", None))
        self.export_options_tab_widget.setTabText(self.export_options_tab_widget.indexOf(self.export_options_game_tab), QCoreApplication.translate("MainWindow", u"Game", None))
        pass
    # retranslateUi

